2019-02-11 21:34:52,017 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-11 21:37:29,151 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-16 16:08:01,288 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-16 16:10:07,696 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-16 16:12:50,915 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-16 16:13:58,979 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-16 16:14:50,962 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-18 14:56:28,384 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-18 15:01:24,889 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-18 15:02:13,172 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-18 15:10:34,745 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-18 15:21:05,817 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-18 15:39:57,243 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-18 15:40:49,780 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-18 15:47:55,847 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-18 15:55:32,340 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-18 16:08:06,319 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-18 16:13:40,112 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-18 21:29:34,476 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-18 21:31:17,103 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-18 22:02:29,611 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-18 22:03:05,601 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-19 06:29:24,735 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-19 06:29:34,206 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-19 06:29:43,328 ERROR: Exception on /login [GET] [in /Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/brianlouie/Desktop/microblog/app/routes.py", line 56, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/brianlouie/Desktop/microblog/app/templates/base.html", line 13, in template
    <a href="{{ ur;_for('explore') }}">Explore</a>
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/Users/brianlouie/Desktop/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/brianlouie/Desktop/microblog/app/templates/base.html", line 13, in template
    <a href="{{ ur;_for('explore') }}">Explore</a>
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 876, in subparse
    self.stream.expect('variable_end')
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/jinja2/lexer.py", line 384, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got ';'
2019-02-19 06:32:36,522 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-19 06:32:53,249 ERROR: Exception on / [GET] [in /Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/brianlouie/Desktop/microblog/app/routes.py", line 24, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2019-02-19 06:33:14,595 ERROR: Exception on / [GET] [in /Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/brianlouie/Desktop/microblog/app/routes.py", line 24, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
